# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dandan website
email: pigpig336699@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  > 歡迎光臨 <

blurb: <strong>Hellow My name is 康皓</strong> 
    This is my own WebSite and I am good at HTML/CSS/JS
    I think....
    And if you want to contnect me
    My E-mail :pigpig336699@gmail.com

bg-img: hero-bg.jpg


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
port: 8080
host: 127.0.0.1 

#_______________work DIV________________

